version: "2"

services:
  postgres:
    container_name: photonix-postgres
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: photonix
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    container_name: photonix-redis
    image: redis:3.2.8
    ports:
      - "6379:6379"

  photonix:
    container_name: photonix
    # image: damianmoore/photonix:latest
    build:
      context: .
    ports:
     - "8888:80"
     - "8889:8000"
    environment:
      ENV: dev
      POSTGRES_HOST: postgres
      POSTGRES_DB: photonix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
    volumes:
     - ./backend:/srv/backend
     - ./ui/public:/srv/ui/public
     - ./ui/src:/srv/ui/src
     - ./ui/static:/srv/ui/static
     - ./data/photos:/data/photos
     - ./data/raw-photos-processed:/data/raw-photos-processed
     - ./data/cache:/data/cache
     - ./data/models:/data/models
     - ./system/supervisord.conf:/etc/supervisord.conf
    links:
     - postgres
     - redis
