version: '3'

services:
  postgres:
    user: "70:70"
    container_name: photonix-postgres
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: photonix
      POSTGRES_PASSWORD: password
    volumes:
      - ../data/db:/var/lib/postgresql/data
    depends_on:
      - init

  redis:
    user: "999:999"
    container_name: photonix-redis
    image: redis:6.2.2
    depends_on:
      - init

  photonix:
    user: "2000:2000"
    container_name: photonix
    # image: photonixapp/photonix:latest
    image: photonix
    build:
      context: ..
      dockerfile: docker/Dockerfile.prd
    ports:
      - '8888:80'
    environment:
      ENV: prd
      POSTGRES_HOST: postgres
      POSTGRES_DB: photonix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
      ALLOWED_HOSTS: '*'
    volumes:
      - ../data/photos:/data/photos
      - ../data/raw-photos-processed:/data/raw-photos-processed
      - ../data/cache:/data/cache
      - ../data/models:/data/models
    links:
      - postgres
      - redis
    depends_on:
      - init
