version: '2'

services:
  postgres:
    container_name: photonix-postgres
    image: postgres:11.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: photonix
      POSTGRES_PASSWORD: password
    volumes:
      - ../data/db:/var/lib/postgresql/data

  redis:
    container_name: photonix-redis
    image: redis:3.2.8
    ports:
      - '6379:6379'

  photonix:
    container_name: photonix
    # image: damianmoore/photonix:latest
    image: photonix-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - '8888:80'
      - '8889:8000'
      - '8880:8001'
    environment:
      ENV: dev
      DEMO: 1
      POSTGRES_HOST: postgres
      POSTGRES_DB: photonix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
      ALLOWED_HOSTS: '*'
    volumes:
      - ../photonix:/srv/photonix
      - ../system:/srv/system
      - ../tests:/srv/tests
      - ../test.py:/srv/test.py
      - ../ui/public:/srv/ui/public
      - ../ui/src:/srv/ui/src
      - ../ui/static:/srv/ui/static
      - ../ui/package.json:/srv/ui/package.json
      - ../ui/yarn.lock:/srv/ui/yarn.lock
      - ../ui/config:/srv/ui/config
      - ../ui/scripts:/srv/ui/scripts
      - ../data/photos:/data/photos
      - ../data/raw-photos-processed:/data/raw-photos-processed
      - ../data/cache:/data/cache
      - ../data/models:/data/models
      - ../system/supervisord.conf:/etc/supervisord.conf
    links:
      - postgres
      - redis
